image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080 # Vue App
    onOpen: open-preview

vscode:
  extensions:
    - wakatime.vscode-wakatime
    - vscode-icons-team.vscode-icons
    - vscodevim.vim
    - coenraads.bracket-pair-colorizer
    - dbaeumer.vscode-eslint
    - ms-vscode.vscode-typescript-tslint-plugin
    - octref.vetur

tasks:
  - init: yarn install
    command: yarn